# .github/workflows/qodana.yml
name: Qodana Scan

on:
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3 # バージョンは適宜更新